### ISSUE TITLE
rainlab blog page throw exception error

### ISSUE THREAD

**Issue by cubakcabak** [mstrrain/Arcane-SEO#1]
![image](https://user-images.githubusercontent.com/12022934/60766646-d5af6d00-a0d6-11e9-9e39-cc8d377a12b1.png)

this occurs when seo dynamic meta title is left as is (blank) in blog in the existing blogpost before the seo plugin installed

update: opening the blog and then saving it makes the exception error gone
maybe the plugin need to fill in [arcane_seo_options] column in [rainlab_blog_posts] table with default "blank variable": {"meta_title":"","meta_description":"","canonical_url":"","robot_index":"","robot_follow":"","robot_advanced":"","enabled_in_sitemap":"0","og_title":"","og_description":"","og_type":"","og_image":"","og_ref_image":""}

**Comment by mstrrain** [comment]
Thank you, will update soon!

**Comment by mstrrain** [comment]
fixed
